### ISSUE TITLE
in directions resource, return a more structured directions object so that it is easier to customize in application

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#199] opened 2019-11-19 02:34 UTC
Requested by Vivid Solutions for use in TransLink Commercial Vehicle Router Application

Enhancement request received by email as follows:

Sent: Monday, November 18, 2019 1:02 PM
To: bcgov/ols-router
Cc: Subscribed
Subject: [bcgov/ols-router] In a directions request, the text in the directions result structure should be given more semantic hints. (#197)
 
The entries in the directions list in a typical result of a 'directions' request look like:

       {
            "type": "CONTINUE",
            "text": "Continue onto Swartz Bay Ferry Terminal for 75 m (27 seconds)",
            "point": [
                -123.41091,
                48.68861
            ]
        }
The text contains at least 4 separate pieces of information:

type of direction
destination
distance
expected time
Only one of these is provided as a separate property (type).
The other pieces of infomation are formatted in text and hence are made more difficult than it needs to be to format this information in an application-specific way.

Describe the solution you'd like

I want to see the other parts of the text broken out into their own properties:

       {
            "type": "CONTINUE",
            "destination": "Swartz Bay Ferry Terminal",
            "distance": 75 // always in meters
            "time": 27 // always in seconds
            "text": "Continue onto Swartz Bay Ferry Terminal for 75 m (27 seconds)",
            "point": [
                -123.41091,
                48.68861
            ]
        }
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cmhodgson** [comment] 2019-11-19 16:53
Duplicate of #197.

**Closed by cmhodgson** 2019-11-19 16:53 UTC
