### ISSUE TITLE
Add support for segment Id list in notification restriction

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-router#207] opened 2020-01-17 23:29 UTC
In the response from the BC Route Planner /truck/directions resource described in ([ols-router/issues/204](https://github.com/bcgov/ols-router/issues/204)) include a list of segment IDs for each notification restriction. 

This will enable client applications to provide additional feedback to the user.

**Comment by cmhodgson** [comment] 2020-01-21 00:07
The router does not currently store TLID values, and it does not output any kind of segment ID. If the intent is to attach the notification to a portion of the route line geometry, one approach would be to  use the notification section in the directions, as is currently used for ferry waits and road closure delays - however this would only identify a point (the point where the notification starts to apply to the route) - not a linear sub-segment of the route.

**Comment by alixcote** [comment] 2022-12-29 19:13
Duplicate of the TLIDS #355 . Closing.

**Closed by alixcote** 2022-12-29 19:13 UTC
Labels: enhancement, ROUTE PLANNER, truck routing
