### ISSUE TITLE
In find route, add support for relaxing specific restrictions

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-router#160] opened 2019-03-13 23:36 UTC
Add support for a relax parameter that allows a request to specify a list of individual restrictions that should be ignored when computing a constrained route. The resulting directions should include notifications of all violated restrictions. A list of violated restrictions should also be returned.

Restrictions that can be relaxed include turn-restrictions, one-ways, and road restrictions (e.g., height, weight, and width)

This will allow users with local knowledge to override incorrect restriction data. LS001

**Comment by alixcote** [comment] 2022-12-29 18:49
Duplicate of 301 - closing.

**Closed by alixcote** 2022-12-29 18:49 UTC
Labels: enhancement, advanced route planning, api, medium priority, restriction-aware routing, functional route planner, truck routing
